### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by meaningfool** [fattenap/react-autolayout#1]
Hello,

I want to take some time to try this out, what is the current state of development ? Is it usable ? 

Also regarding the documentation, there are 2 things that I don't quite understand : 
- In the query, the condition constraints.demo.page.width < 600 references the viewkey of the layout that is currently being "evaluated". If it is the somewhat equivalent to media queries, I would have expected the condition to be set on the viewport...?
- I also don' understand the "Caveat" part. Could you be a little more explicit about what would not work ? 

Thank you for the work, I really find autolayout interesting and it's great to be able to combine it with react...

**Comment by fattenap** [comment]
Hi meaningfool,

Firstly thanks for your interest in the project. The project is in it's early days and is untested. There are still changes to come that will change the API, and most likely breaking changes, so you may want to hold off from using it in production.

The concept of the query function is that it allows you to set break points at the element\view level as opposed to the viewport. This allows for more flexibility in layouts. The constraints parameter that gets passed in holds all the defined views widths and heights, so that you can reference them when deciding how to layout your views.

With regards to the caveats. React-autolayout is based on [autolayout.js](https://github.com/IjzerenHein/autolayout.js) - developed by @IjzerenHein. It uses some properties that are currently not supported by React-AutoLayout, like Z Ordering and meta comments. But I'm currently addressing those. With regards to the css style reference's, those attributes are used by autolayout to layout the views. So you cannot set those values directly on the view you are creating. However, any child elements inside the element specified with the `viewKey` can be styled.

I hope that clarifies it a little, but I hope to add more to the documentation with some sample code in the coming weeks, once I firm up some concepts.

Again, download it, play around, provide feedback, but be warned it still in alpha.

Thanks
Frank

**Comment by meaningfool** [comment]
Alright, I'll be watching. I also wonder for now how to compose with motion / transition modules...

Cheers,
Josselin

**Comment by fattenap** [comment]
I will be investigating that also. So stay tuned.
